# renpyable.py - Simple python programme to rename TIF files
# (generated for Trueflow RIP) for better sort ability.
__author__ = 'propbono'
# E-mail: propbono@gmail.com
#

import os
from config import RealConfig
from rename import Rename


class Renpyable:
    def __init__(self, config):
        """
            Initialization method
            creates and assign necessary values from configuration file.
            tif_directory - directory where tiff files are stored
            doa_directory - whole disk with customers jobs where *Doa.pdf files are stored
            ppf_directory - directory where cip3 (ppf) files are stored
            pdf_to_ppf_directory - directory where pdf files used to create ppf files are stored
            version - variable responsible for keeping version program
        """
        self.version = config.VERSION
        self.tif_directory = config.TIF_DIRECTORY
        self.doa_directory = config.DOA_DIRECTORY
        self.ppf_directory = config.PPF_DIRECTORY
        self.pdf_to_ppf_directory = config.PDF_ARCHIVE_DIRECTORY
        self.directories = {self.tif_directory, self.doa_directory,
                            self.ppf_directory, self.pdf_to_ppf_directory}

    def correct_tiff_filenames(self, digits):
        """
            Function lit every file in folder TIF_DIRECTORY from config file
            and of every file execute function Rename.correct_filename(name,digits)
            which changes name accordingly: uppercase to smallcase,  word front to afront,
            numbering convention from 1, 2, 3 to 001, 002, 003 if digits = 3

            :param digits:
        """
        file_list = os.listdir(self.tif_directory)
        file_renamed_count = 0
        file_in_list_count = len(file_list)
        for name in file_list:
            new_name =  Rename.correct_filename(name, digits)
            if name.__ne__(new_name):
                os.rename(self.tif_directory + name, self.tif_directory + new_name)
                file_renamed_count += 1
        print("Files in folder: " + str(file_in_list_count) + "\nFiles changed: " +
               str(file_renamed_count))


if __name__ == "__main__":
    renpyable = Renpyable(RealConfig())

    print()
    print("TIFF name changer v.", renpyable.version)
    print("This programme let you change name of TIF files generated by "
             "Trueflow.\nChoose what do you want to do:\n")
    print("Correct File names i.e. 1 = 1, 2 = 02, 3 = 003 | "
              "AFRONT instead FRONT etc.")
    digits = input("How many digits will have new number?: ")
    renpyable.correct_tiff_filenames(int(digits))

